# Generated by Django 5.1.3 on 2024-11-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('set_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Set Temp')),
                ('current_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Current Temp')),
            ],
        ),
    ]
