# Generated by Django 5.1.3 on 2024-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('time_point', models.DateTimeField(verbose_name='Time Point')),
                ('specific_gravity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Specific Gravity')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('beer', models.CharField(max_length=100, verbose_name='Beer')),
                ('comment', models.TextField(max_length=200, verbose_name='Comment')),
            ],
        ),
    ]
