# Generated by Django 5.1.3 on 2024-11-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fermdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempData',
            new_name='TemperatureData',
        ),
    ]
