# Generated by Django 5.1.3 on 2024-11-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_tempdata_temperaturedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FermData',
            new_name='FermentationData',
        ),
    ]
