# Generated by Django 5.1.3 on 2024-11-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_fermdata_fermentationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentationdata',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='fermentationdata',
            name='time_point',
        ),
    ]
