# Generated by Django 5.1.3 on 2024-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_fermentationdata_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentationdata',
            name='time_stamp',
            field=models.DateField(verbose_name='Time Stamp'),
        ),
    ]
