# Generated by Django 5.1.3 on 2024-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_fermentationdata_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentationdata',
            name='time_stamp',
            field=models.DateTimeField(verbose_name='Time Stamp'),
        ),
    ]
