# Generated by Django 5.1.3 on 2024-11-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_fermentationdata_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentationdata',
            name='time_stamp',
            field=models.CharField(max_length=20, verbose_name='Time Stamp'),
        ),
    ]
