# Generated by Django 5.1.3 on 2024-11-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_fermentationdata_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationdata',
            name='time_point',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Timepoint'),
        ),
    ]
