# Generated by Django 5.1.3 on 2024-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fermentationdata_time_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetSourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceURL', models.CharField(max_length=250, verbose_name='SourceURL')),
            ],
        ),
    ]
