# Generated by Django 5.1.3 on 2024-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_googlesheetsourcedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetsourcedata',
            name='readable_name',
            field=models.CharField(default='N/A', max_length=250, verbose_name='readableName'),
        ),
    ]
