# Generated by Django 5.1.3 on 2024-12-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_googlesheetsourcedata_readable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetsourcedata',
            name='readable_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Readable Name'),
        ),
        migrations.AlterField(
            model_name='googlesheetsourcedata',
            name='sourceURL',
            field=models.CharField(max_length=250, unique=True, verbose_name='SourceURL'),
        ),
    ]
