# Generated by Django 5.1.3 on 2024-12-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_googlesheetsourcedata_readable_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDataSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.CharField(max_length=250, unique=True, verbose_name='user_profile')),
                ('selected_google_sheet', models.CharField(max_length=250, unique=True, verbose_name='Readable Name')),
            ],
        ),
    ]
