# Generated by Django 5.1.3 on 2025-04-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_profiledataselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermentationDataTilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('gravity', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
