# Generated by Django 5.1.3 on 2025-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_fermentationdatatilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationdatatilt',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
